const Backend = {
  api: import.meta.env.VITE_PMS_URL,
  auth: import.meta.env.VITE_AUTH_URL,
  users: 'users',
  refreshToken: 'refresh',
  resetPassword: 'reset-password',
  setPassword: 'create-password',
  verifyOtp: 'verify-otp',
  myProfile: 'my-profile',
  changePassword: 'change-password',
  updateProfileImage: 'update-profile-image',
  removeProfileImage: 'remove-profile-image',
  roles: 'roles',
  units: 'units',
  unitByTypes: 'unit-by-type/',
  types: 'unit-types',
  employees: 'employees',
  employeeExcel: 'import-employee-excel',
  kpi: 'kpis',
  getStats: 'get-counts',
  preSetups: 'kpi-pre-setups',
  fiscalYear: 'get-fiscal-year',
  periods: 'periods',
  frequencies: 'frequencies',
  planningPeriods: 'get-planing-period',
  planningFrequiencies: 'get-planing-frequencies',
  orgPlan: 'main-kpi-tracking',
  showPlan: 'show-plan',
  deletePlan: 'delete-plan',
  getOrgPlans: 'get-my-kpi-trackings',
  distributeTarget: 'distribute-kpi-tracking',
  childUnits: 'get-my-child-units',
  childTarget: 'get-my-child-targets/',
  getDepartments: 'get-departments',
  getActiveDepartments: 'get-active-departments',
  getEmployees: 'get-employees',
  getActiveEmployees: 'get-active-employees',
  getManagers: 'get-managers',
  getUnitTarget: 'get-tasks-by-unit/',
  getEmployeeTarget: 'get-tasks-by-employee/',
  evaluate: 'evaluate',
  employeePerformance: 'employee-performance/',
  unitPerformance: 'unit-performance/',
  myPerformance: 'my-performance',
  myUnitPerformance: 'my-unit-performance',

  workflows: 'workflows',
  createWorkflow: 'create-workflow',
  updateWorkflow: 'update-workflow',
  deleteWorkflow: 'delete-workflow',

  /**Eyuel Endpoints */
  permissi: 'permissions',
  role: 'roles',
  fiscal_years: 'fiscal-years',
  planning_periods: 'create-planning-period',
  frequency_period_values: 'create-frequency-definition-period',
  evaluation_periods: 'create-evaluation-period',
  eodfetch: 'end-of-day-activities'
};
export default Backend;
