const Backend = {
  //   api: 'https://localhost:8000/api/',
  api: 'https://droga-pms.amanueld.info/api/',
  auth: 'https://droga-auth.amanueld.info/api/',
  resetPassword: 'reset-password',
  setPassword: 'create-password',
  verifyOtp: 'verify-otp',
  myProfile: 'my-profile',
  changePassword: 'change-password',
  updateProfileImage: 'update-profile-image',
  removeProfileImage: 'remove-profile-image',
  roles: 'roles',
  units: 'units',
  types: 'unit-types',
  employees: 'employees',
  employeeExcel: 'import-employee-excel',
  kpi: 'kpis',
  getStats: 'get-counts',
  preSetups: 'kpi-pre-setups',
  fiscalYear: 'get-fiscal-year',
  periods: 'periods',
  frequencies: 'frequencies',
  planningPeriods: 'get-planing-period',
  orgPlan: 'main-kpi-tracking',
  getOrgPlans: 'get-my-kpi-trackings',
  distributeTarget: 'distribute-kpi-tracking',
  childUnits: 'get-my-child-units',
  childTarget: 'get-my-child-targets/',
  getDepartments: 'get-departments',
  getEmployees: 'get-employees',
  getManagers: 'get-managers',
  getUnitTarget: 'get-tasks-by-unit/',
  getEmployeeTarget: 'get-tasks-by-employee/',
  evaluate: 'evaluate'

  // -----------------------------------------------
};
export default Backend;
